package handlers

import (
	"database/sql"
	"html"
	"net/http"
	"net/url"
	"os"
	"strings"

	"gova/app/cache"
	"gova/app/models"
)

const (
	shareDefaultTitle = "ResearchIQ — Shared Research"
	shareDefaultDesc  = "A plain-language summary of the peer-reviewed evidence, generated by ResearchIQ."
)

// ShareGET serves the public share page, injecting real og/twitter meta
// tags server-side so link-preview bots (iMessage, Slack, etc.) — which
// don't execute JS — see the actual research topic instead of generic
// placeholder text.
func ShareGET(readDB, writeDB *sql.DB, appCache *cache.Cache) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		page, err := os.ReadFile("./static/pages/share.html")
		if err != nil {
			http.NotFound(w, r)
			return
		}

		title := shareDefaultTitle
		desc := shareDefaultDesc
		token := r.URL.Query().Get("t")

		if token != "" {
			jobModel := models.NewResearchJobModel(readDB, writeDB, appCache)
			if job, err := jobModel.FindByShareToken(token); err == nil && job != nil && job.Status == "done" {
				title = shareDisplayTitle(job)
				resultModel := models.NewResearchResultModel(readDB, writeDB, appCache)
				if result, err := resultModel.GetByJobID(job.ID); err == nil && result != nil {
					if d := shareDescSnippet(result.Summary); d != "" {
						desc = d
					}
				}
			}
		}

		appURL := os.Getenv("APP_URL")
		ogURL := appURL + "/share"
		if token != "" {
			ogURL += "?t=" + url.QueryEscape(token)
		}
		ogImage := appURL + "/static/img/og-image.png"

		out := string(page)
		out = strings.ReplaceAll(out, "__OG_TITLE__", html.EscapeString(title))
		out = strings.ReplaceAll(out, "__OG_DESC__", html.EscapeString(desc))
		out = strings.ReplaceAll(out, "__OG_URL__", html.EscapeString(ogURL))
		out = strings.ReplaceAll(out, "__OG_IMAGE__", html.EscapeString(ogImage))

		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.Write([]byte(out))
	}
}

func shareDisplayTitle(job *models.ResearchJob) string {
	if job.Title != "" {
		return truncateRunes(job.Title, 80)
	}
	return truncateRunes(job.Question, 80)
}

func shareDescSnippet(summary string) string {
	s := strings.Join(strings.Fields(summary), " ")
	if s == "" {
		return ""
	}
	return truncateRunes(s, 200)
}

func truncateRunes(s string, n int) string {
	r := []rune(s)
	if len(r) <= n {
		return s
	}
	return strings.TrimSpace(string(r[:n])) + "…"
}
